name: alan-nz
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.1.4
  - geopandas=0.13.2
  - shapely=1.8.5
  - rasterio=1.3.8
  - rioxarray=0.15.5
  - pyproj=3.6.1
  - fiona=1.9.6
  - gdal=3.6.*
  - rasterstats=0.19.0
  - requests
  - openpyxl
  - tqdm
  - pip
  - pip:
      - plotly==5.22.0
      - streamlit==1.33.0